In [183]:
from selenium import webdriver
import urllib.request as req
from bs4 import BeautifulSoup
import pandas as pd

In [185]:
driver = webdriver.Chrome('./chromedriver')
driver.get('http://www.football-lineups.com/match/74983/')

WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

In [179]:
html = driver.page_source
soup = BeautifulSoup(html,'html.parser')
team1 = soup.select('#mainarea > tbody > tr > td.TDmain > table > tbody > tr > td > font > b' )[0].text
team2 = soup.select('#mainarea > tbody > tr > td.TDmain > table > tbody > tr > td > font > b' )[1].text
print(team1)
print(team2)

Australia
Bahrain

In [157]:
html = driver.page_source
soup = BeautifulSoup(html,'html.parser')
time = soup.select('#mainarea > tbody > tr > td.TDmain > table > tbody > tr > td' )[6].text.split()
print(time[0:2])
print(time[1])

['11-Jan-11', '16:15']
16:15

In [158]:
html = driver.page_source
soup = BeautifulSoup(html,'html.parser')
weather = soup.select('#mainarea > tbody > tr > td.TDmain > table > tbody > tr > td > font' )[3:]
print(weather[0].text)
print(weather[1].text)

 9:28 am AST  Fair 18C
 4:28 pm AST  Fair 20C

In [159]:
html = driver.page_source
soup = BeautifulSoup(html,'html.parser')
detail = soup.select('#mainarea > tbody > tr > td.TDmain > table >\
                   tbody > tr > td > table > tbody > tr > td > table > tbody > tr > td' )[186:]
print(detail[3].text)
print(detail[4].text)
print(detail[5].text)
print(detail[6].text)
print(detail[7].text)
print(detail[8].text)
print(detail[15].text)
print(detail[16].text)
print(detail[17].text)

Shots on gol
5
21
Fouls
11
2
Time %
48

In [ ]:
74983,75006

In [192]:
driver = webdriver.Chrome('./chromedriver')
team1List = []
team2List = []
timeList = []
weather1List = []
weather2List = []
Shots1List = []
Shots2List = []
Fouls1List = []
Fouls2List = []
possession1List = []
possession2List = []

for i in range(74983,75004):
    url_base = 'http://www.football-lineups.com/match/'
    url_sub = str(i)
    driver.get(url_base + url_sub)
    html = driver.page_source
    soup = BeautifulSoup(html,'html.parser')
    team1 = soup.select('#mainarea > tbody > tr > td.TDmain > table > tbody > tr > td > font > b' )[0].text
    team1List.append(team1)
    team2 = soup.select('#mainarea > tbody > tr > td.TDmain > table > tbody > tr > td > font > b' )[1].text
    team2List.append(team2)
    time = soup.select('#mainarea > tbody > tr > td.TDmain > table > tbody > tr > td' )[6].text.split()
    timeList.append(time[0:2])
    weather = soup.select('#mainarea > tbody > tr > td.TDmain > table > tbody > tr > td > font' )[3:]
    weather1List.append(weather[0].text)
    weather2List.append(weather[1].text)
    detail = soup.select('#mainarea > tbody > tr > td.TDmain > table >\
                   tbody > tr > td > table > tbody > tr > td > table > tbody > tr > td' )[186:]
    Shots1List.append(detail[3].text)
    Shots2List.append(detail[5].text)
    Fouls1List.append(detail[6].text)
    Fouls2List.append(detail[8].text)
    possession1List.append(detail[15].text)
    possession2List.append(detail[17].text)

In [193]:
print(team1List)
print(team2List)
print(timeList)
print(weather1List)
print(weather2List)
print(Shots1List)
print(Shots2List)
print(Fouls1List)
print(Fouls2List)
print(possession1List)
print(possession2List)

['Qatar', 'Kuwait', 'Japan', 'Saudi Arabia', 'India', 'South Korea', 'North Korea', 'Iraq', 'Uzbekistan', 'China, PR', 'Jordan', 'Syria', 'Australia', 'Bahrain', 'Iran', 'United Arab Emirates', 'Qatar', 'China, PR', 'Saudi Arabia', 'Jordan', 'South Korea']
['Uzbekistan', 'China, PR', 'Jordan', 'Syria', 'Australia', 'Bahrain', 'United Arab Emirates', 'Iran', 'Kuwait', 'Qatar', 'Saudi Arabia', 'Japan', 'South Korea', 'India', 'North Korea', 'Iraq', 'Kuwait', 'Uzbekistan', 'Japan', 'Syria', 'India']
[['07-Jan-11', '19:15'], ['08-Jan-11', '16:15'], ['09-Jan-11', '16:15'], ['09-Jan-11', '19:15'], ['10-Jan-11', '16:15'], ['10-Jan-11', '19:15'], ['11-Jan-11', '16:15'], ['11-Jan-11', '19:15'], ['12-Jan-11', '16:15'], ['12-Jan-11', '19:15'], ['13-Jan-11', '16:15'], ['13-Jan-11', '19:15'], ['14-Jan-11', '16:15'], ['14-Jan-11', '19:15'], ['15-Jan-11', '16:15'], ['15-Jan-11', '19:15'], ['16-Jan-11', '19:15'], ['16-Jan-11', '19:15'], ['17-Jan-11', '16:15'], ['17-Jan-11', '16:15'], ['18-Jan-11', '16:15']]
[' 8:28 am AST  Sunny 20C', ' 11:00 am AST  Partly Cloudy 23C', ' 6:58 am AST  Fog 17C', ' 11:59 am AST  Partly Cloudy 24C', ' 9:28 am AST  Sunny 21C', ' 12:59 pm AST  Partly Cloudy 24C', ' 9:28 am AST  Fair 18C', ' 12:29 pm AST  Fair 21C', ' 12:29 pm AST  Partly Cloudy 21C', ' 12:29 pm AST  Partly Cloudy 21C', ' 11:59 am AST  Fair 19C', ' 11:59 am AST  Fair 19C', ' 7:58 am AST  Fair 15C', ' 8:28 am AST  Fair 15C', ' 11:59 am AST  Partly Cloudy 23C', ' 11:59 am AST  Partly Cloudy 23C', ' 12:29 pm AST  Sunny 24C', ' 12:29 pm AST  Sunny 24C', ' 12:59 pm AST  Fair 20C', ' 12:59 pm AST  Fair 20C', ' 10:00 am AST  Light Rain 19C']
[' 7:00 pm AST  Clear 21C', ' 4:28 pm AST  Sunny 23C', ' 5:06 pm AST  Mostly Cloudy/Windy 21C', ' 7:00 pm AST  Clear 20C', ' 4:28 pm AST  Fair 21C', ' 7:29 pm AST  Fair 19C', ' 4:28 pm AST  Fair 20C', ' 8:59 pm AST  Fair 17C', ' 4:28 pm AST  Partly Cloudy 19C', ' 7:29 pm AST  Fair 17C', ' 10:58 pm AST  Fair 15C', ' 11:28 pm AST  Fair 15C', ' 5:28 pm AST  Fair 18C', ' 7:29 pm AST  Fair 18C', ' 7:29 pm AST  Fair 20C', ' 7:00 pm AST  Fair 20C', ' 9:29 pm AST  Clear 19C', ' 9:29 pm AST  Clear 19C', ' 4:58 pm AST  Fair 19C', ' 7:00 pm AST  Mostly Cloudy 18C', ' 5:28 pm AST  Light Rain 16C']
['4', '2', '7', '3', '2', '5', 'Shots on gol ', '3', '2', '5', '3', '', '4', '9', '2', 'Shots on gol ', '6', '7', '3', '1', '20']
['7', '6', '2', '3', '9', '6', '21', '6', '3', '4', '4', '', '7', '6', '4', '7', '1', '7', '9', '7', '4']
['15', '17', '13', '13', '10', '17', 'Fouls ', '25', '27', '15', '17', '\xa0\xa0\xa0', '14', '15', '26', 'Fouls ', '23', '17', '7', '17', '9']
['13', '23', '14', '17', '12', '19', '2', '19', '14', '16', '19', '', '16', '11', '22', '8', '16', '20', '23', '19', '17']
['45', '51', '68', '55', '35', '62', 'Time % ', '39', '52', '49', '47', '', '45', '62', '49', 'Time % ', '43', '35', '48', '38', '65']
['55', '49', '32', '45', '65', '38', '', '61', '48', '51', '53', '\xa0\xa0\xa0', '55', '38', '51', '', '57', '65', '52', '62', '35']

In [194]:
len(ShotsList)

60

In [195]:
gamedetail_2011 = pd.DataFrame(team1List)
gamedetail_2011 = gamedetail_2011.rename(columns = {0:'team1'})
gamedetail_2011['team2'] = team2List
gamedetail_2011['gameday'] = timeList
gamedetail_2011['weather_d'] = weather1List
gamedetail_2011['weather_t'] = weather2List
gamedetail_2011['shoot1'] = Shots1List
gamedetail_2011['shoot2'] = Shots2List
gamedetail_2011['foul1'] = Fouls1List
gamedetail_2011['foul2'] = Fouls2List
gamedetail_2011['possession1'] = possession1List
gamedetail_2011['possession2'] = possession2List

In [196]:
gamedetail_2011

,team1,team2,gameday,weather_d,weather_t,shoot1,shoot2,foul1,foul2,possession1,possession2
0,Qatar,Uzbekistan,"[07-Jan-11, 19:15]",8:28 am AST Sunny 20C,7:00 pm AST Clear 21C,4,7,15,13,45,55
1,Kuwait,"China, PR","[08-Jan-11, 16:15]",11:00 am AST Partly Cloudy 23C,4:28 pm AST Sunny 23C,2,6,17,23,51,49
2,Japan,Jordan,"[09-Jan-11, 16:15]",6:58 am AST Fog 17C,5:06 pm AST Mostly Cloudy/Windy 21C,7,2,13,14,68,32
3,Saudi Arabia,Syria,"[09-Jan-11, 19:15]",11:59 am AST Partly Cloudy 24C,7:00 pm AST Clear 20C,3,3,13,17,55,45
4,India,Australia,"[10-Jan-11, 16:15]",9:28 am AST Sunny 21C,4:28 pm AST Fair 21C,2,9,10,12,35,65
5,South Korea,Bahrain,"[10-Jan-11, 19:15]",12:59 pm AST Partly Cloudy 24C,7:29 pm AST Fair 19C,5,6,17,19,62,38
6,North Korea,United Arab Emirates,"[11-Jan-11, 16:15]",9:28 am AST Fair 18C,4:28 pm AST Fair 20C,Shots on gol,21,Fouls,2,Time %,
7,Iraq,Iran,"[11-Jan-11, 19:15]",12:29 pm AST Fair 21C,8:59 pm AST Fair 17C,3,6,25,19,39,61
8,Uzbekistan,Kuwait,"[12-Jan-11, 16:15]",12:29 pm AST Partly Cloudy 21C,4:28 pm AST Partly Cloudy 19C,2,3,27,14,52,48
9,"China, PR",Qatar,"[12-Jan-11, 19:15]",12:29 pm AST Partly Cloudy 21C,7:29 pm AST Fair 17C,5,4,15,16,49,51
10,Jordan,Saudi Arabia,"[13-Jan-11, 16:15]",11:59 am AST Fair 19C,10:58 pm AST Fair 15C,3,4,17,19,47,53
11,Syria,Japan,"[13-Jan-11, 19:15]",11:59 am AST Fair 19C,11:28 pm AST Fair 15C,,,,,,
12,Australia,South Korea,"[14-Jan-11, 16:15]",7:58 am AST Fair 15C,5:28 pm AST Fair 18C,4,7,14,16,45,55
13,Bahrain,India,"[14-Jan-11, 19:15]",8:28 am AST Fair 15C,7:29 pm AST Fair 18C,9,6,15,11,62,38
14,Iran,North Korea,"[15-Jan-11, 16:15]",11:59 am AST Partly Cloudy 23C,7:29 pm AST Fair 20C,2,4,26,22,49,51
15,United Arab Emirates,Iraq,"[15-Jan-11, 19:15]",11:59 am AST Partly Cloudy 23C,7:00 pm AST Fair 20C,Shots on gol,7,Fouls,8,Time %,
16,Qatar,Kuwait,"[16-Jan-11, 19:15]",12:29 pm AST Sunny 24C,9:29 pm AST Clear 19C,6,1,23,16,43,57
17,"China, PR",Uzbekistan,"[16-Jan-11, 19:15]",12:29 pm AST Sunny 24C,9:29 pm AST Clear 19C,7,7,17,20,35,65
18,Saudi Arabia,Japan,"[17-Jan-11, 16:15]",12:59 pm AST Fair 20C,4:58 pm AST Fair 19C,3,9,7,23,48,52
19,Jordan,Syria,"[17-Jan-11, 16:15]",12:59 pm AST Fair 20C,7:00 pm AST Mostly Cloudy 18C,1,7,17,19,38,62
20,South Korea,India,"[18-Jan-11, 16:15]",10:00 am AST Light Rain 19C,5:28 pm AST Light Rain 16C,20,4,9,17,65,35

In [198]:
# driver = webdriver.Chrome('./chromedriver')
team1List = []
team2List = []
timeList = []
weather1List = []
weather2List = []
Shots1List = []
Shots2List = []
Fouls1List = []
Fouls2List = []
possession1List = []
possession2List = []

# for i in range(75004):
#     url_base = 'http://www.football-lineups.com/match/'
#     url_sub = str(i)
#     driver.get(url_base + url_sub)
html = driver.page_source
soup = BeautifulSoup(html,'html.parser')
team1 = soup.select('#mainarea > tbody > tr > td.TDmain > table > tbody > tr > td > font > b' )[0].text
team1List.append(team1)
team2 = soup.select('#mainarea > tbody > tr > td.TDmain > table > tbody > tr > td > font > b' )[1].text
team2List.append(team2)
time = soup.select('#mainarea > tbody > tr > td.TDmain > table > tbody > tr > td' )[6].text.split()
timeList.append(time[0:2])
weather = soup.select('#mainarea > tbody > tr > td.TDmain > table > tbody > tr > td > font' )[3:]
weather1List.append(weather[0].text)
#     weather2List.append(weather[1].text)
detail = soup.select('#mainarea > tbody > tr > td.TDmain > table >\
                   tbody > tr > td > table > tbody > tr > td > table > tbody > tr > td' )[186:]
Shots1List.append(detail[3].text)
Shots2List.append(detail[5].text)
Fouls1List.append(detail[6].text)
Fouls2List.append(detail[8].text)
possession1List.append(detail[15].text)
possession2List.append(detail[17].text)

In [203]:
print(team1List)
print(team2List)
print(timeList)
print(weather1List)
print(weather2List)
print(Shots1List)
print(Shots2List)
print(Fouls1List)
print(Fouls2List)
print(possession1List)
print(possession2List)

['Australia']
['Bahrain']
[['18-Jan-11', '16:15']]
[' 12:59 pm AST  Mostly Cloudy 19C']
['0']
['5']
['4']
['18']
['10']
['46']
['54']

In [202]:
weather2List = ['0']

In [204]:
gamedetail_aus_2011 = pd.DataFrame(team1List)
gamedetail_aus_2011 = gamedetail_aus_2011.rename(columns = {0:'team1'})
gamedetail_aus_2011['team2'] = team2List
gamedetail_aus_2011['gameday'] = timeList
gamedetail_aus_2011['weather_d'] = weather1List
gamedetail_aus_2011['weather_t'] = weather2List
gamedetail_aus_2011['shoot1'] = Shots1List
gamedetail_aus_2011['shoot2'] = Shots2List
gamedetail_aus_2011['foul1'] = Fouls1List
gamedetail_aus_2011['foul2'] = Fouls2List
gamedetail_aus_2011['possession1'] = possession1List
gamedetail_aus_2011['possession2'] = possession2List

In [208]:
gamedetail_aus_2011

,team1,team2,gameday,weather_d,weather_t,shoot1,shoot2,foul1,foul2,possession1,possession2
0,Australia,Bahrain,"[18-Jan-11, 16:15]",12:59 pm AST Mostly Cloudy 19C,0,5,4,18,10,46,54

In [209]:
gamedetail_2011_t = pd.concat([gamedetail_2011,gamedetail_aus_2011])

In [212]:
# driver = webdriver.Chrome('./chromedriver')
team1List = []
team2List = []
timeList = []
weather1List = []
weather2List = []
Shots1List = []
Shots2List = []
Fouls1List = []
Fouls2List = []
possession1List = []
possession2List = []

for i in range(75005,75007):
    url_base = 'http://www.football-lineups.com/match/'
    url_sub = str(i)
    driver.get(url_base + url_sub)
    html = driver.page_source
    soup = BeautifulSoup(html,'html.parser')
    team1 = soup.select('#mainarea > tbody > tr > td.TDmain > table > tbody > tr > td > font > b' )[0].text
    team1List.append(team1)
    team2 = soup.select('#mainarea > tbody > tr > td.TDmain > table > tbody > tr > td > font > b' )[1].text
    team2List.append(team2)
    time = soup.select('#mainarea > tbody > tr > td.TDmain > table > tbody > tr > td' )[6].text.split()
    timeList.append(time[0:2])
    weather = soup.select('#mainarea > tbody > tr > td.TDmain > table > tbody > tr > td > font' )[3:]
    weather1List.append(weather[0].text)
    weather2List.append(weather[1].text)
    detail = soup.select('#mainarea > tbody > tr > td.TDmain > table >\
                   tbody > tr > td > table > tbody > tr > td > table > tbody > tr > td' )[186:]
    Shots1List.append(detail[3].text)
    Shots2List.append(detail[5].text)
    Fouls1List.append(detail[6].text)
    Fouls2List.append(detail[8].text)
    possession1List.append(detail[15].text)
    possession2List.append(detail[17].text)

In [213]:
print(team1List)
print(team2List)
print(timeList)
print(weather1List)
print(weather2List)
print(Shots1List)
print(Shots2List)
print(Fouls1List)
print(Fouls2List)
print(possession1List)
print(possession2List)

['Iraq', 'United Arab Emirates']
['North Korea', 'Iran']
[['19-Jan-11', '19:15'], ['19-Jan-11', '19:15']]
[' 12:29 pm AST  Haze 18C', ' 12:29 pm AST  Haze 18C']
[' 7:00 pm AST  Fair 18C', ' 11:58 pm AST  Clear 18C']
['5', '3']
['4', '3']
['18', '18']
['15', '18']
['48', '50']
['52', '50']

In [214]:
gamedetail_two_2011 = pd.DataFrame(team1List)
gamedetail_two_2011 = gamedetail_two_2011.rename(columns = {0:'team1'})
gamedetail_two_2011['team2'] = team2List
gamedetail_two_2011['gameday'] = timeList
gamedetail_two_2011['weather_d'] = weather1List
gamedetail_two_2011['weather_t'] = weather2List
gamedetail_two_2011['shoot1'] = Shots1List
gamedetail_two_2011['shoot2'] = Shots2List
gamedetail_two_2011['foul1'] = Fouls1List
gamedetail_two_2011['foul2'] = Fouls2List
gamedetail_two_2011['possession1'] = possession1List
gamedetail_two_2011['possession2'] = possession2List

In [215]:
gamedetail_two_2011

,team1,team2,gameday,weather_d,weather_t,shoot1,shoot2,foul1,foul2,possession1,possession2
0,Iraq,North Korea,"[19-Jan-11, 19:15]",12:29 pm AST Haze 18C,7:00 pm AST Fair 18C,5,4,18,15,48,52
1,United Arab Emirates,Iran,"[19-Jan-11, 19:15]",12:29 pm AST Haze 18C,11:58 pm AST Clear 18C,3,3,18,18,50,50

In [216]:
gamedetail_2011_t = pd.concat([gamedetail_2011_t,gamedetail_two_2011])

In [218]:
# gamedetail_2011_t.to_csv('./gamedetail_2011.csv',index=False,header=True)

In [219]:
# driver = webdriver.Chrome('./chromedriver')
team1List = []
team2List = []
timeList = []
weather1List = []
weather2List = []
Shots1List = []
Shots2List = []
Fouls1List = []
Fouls2List = []
possession1List = []
possession2List = []

for i in range(94020,94024):
    url_base = 'http://www.football-lineups.com/match/'
    url_sub = str(i)
    driver.get(url_base + url_sub)
    html = driver.page_source
    soup = BeautifulSoup(html,'html.parser')
    team1 = soup.select('#mainarea > tbody > tr > td.TDmain > table > tbody > tr > td > font > b' )[0].text
    team1List.append(team1)
    team2 = soup.select('#mainarea > tbody > tr > td.TDmain > table > tbody > tr > td > font > b' )[1].text
    team2List.append(team2)
    time = soup.select('#mainarea > tbody > tr > td.TDmain > table > tbody > tr > td' )[6].text.split()
    timeList.append(time[0:2])
    weather = soup.select('#mainarea > tbody > tr > td.TDmain > table > tbody > tr > td > font' )[3:]
    weather1List.append(weather[0].text)
    weather2List.append(weather[1].text)
    detail = soup.select('#mainarea > tbody > tr > td.TDmain > table >\
                   tbody > tr > td > table > tbody > tr > td > table > tbody > tr > td' )[186:]
    Shots1List.append(detail[3].text)
    Shots2List.append(detail[5].text)
    Fouls1List.append(detail[6].text)
    Fouls2List.append(detail[8].text)
    possession1List.append(detail[15].text)
    possession2List.append(detail[17].text)

In [220]:
print(team1List)
print(team2List)
print(timeList)
print(weather1List)
print(weather2List)
print(Shots1List)
print(Shots2List)
print(Fouls1List)
print(Fouls2List)
print(possession1List)
print(possession2List)

['Japan', 'Uzbekistan', 'Australia', 'Iran']
['Qatar', 'Jordan', 'Iraq', 'South Korea']
[['21-Jan-11', '16:25'], ['21-Jan-11', '19:25'], ['22-Jan-11', '16:25'], ['22-Jan-11', '16:25']]
[' 11:59 am AST  Mostly Cloudy 17C', ' 11:59 am AST  Mostly Cloudy 17C', ' 11:59 am AST  Partly Cloudy 20C', ' 11:59 am AST  Partly Cloudy 20C']
[' 6:00 pm AST  Mostly Cloudy 17C', ' 6:00 pm AST  Mostly Cloudy 17C', ' 6:30 pm AST  Fair 19C', ' 5:28 pm AST  Partly Cloudy 19C']
['6', '5', '10', '2']
['7', '5', '3', '3']
['17', '11', '28', '27']
['18', '13', '17', '29']
['59', '65', '55', '50']
['41', '35', '45', '50']

In [221]:
gamedetail_qf_2011 = pd.DataFrame(team1List)
gamedetail_qf_2011 = gamedetail_qf_2011.rename(columns = {0:'team1'})
gamedetail_qf_2011['team2'] = team2List
gamedetail_qf_2011['gameday'] = timeList
gamedetail_qf_2011['weather_d'] = weather1List
gamedetail_qf_2011['weather_t'] = weather2List
gamedetail_qf_2011['shoot1'] = Shots1List
gamedetail_qf_2011['shoot2'] = Shots2List
gamedetail_qf_2011['foul1'] = Fouls1List
gamedetail_qf_2011['foul2'] = Fouls2List
gamedetail_qf_2011['possession1'] = possession1List
gamedetail_qf_2011['possession2'] = possession2List

In [222]:
gamedetail_qf_2011

,team1,team2,gameday,weather_d,weather_t,shoot1,shoot2,foul1,foul2,possession1,possession2
0,Japan,Qatar,"[21-Jan-11, 16:25]",11:59 am AST Mostly Cloudy 17C,6:00 pm AST Mostly Cloudy 17C,6,7,17,18,59,41
1,Uzbekistan,Jordan,"[21-Jan-11, 19:25]",11:59 am AST Mostly Cloudy 17C,6:00 pm AST Mostly Cloudy 17C,5,5,11,13,65,35
2,Australia,Iraq,"[22-Jan-11, 16:25]",11:59 am AST Partly Cloudy 20C,6:30 pm AST Fair 19C,10,3,28,17,55,45
3,Iran,South Korea,"[22-Jan-11, 16:25]",11:59 am AST Partly Cloudy 20C,5:28 pm AST Partly Cloudy 19C,2,3,27,29,50,50

In [227]:
gamedetail_2011_t = pd.concat([gamedetail_2011_t,gamedetail_qf_2011])

In [223]:
# driver = webdriver.Chrome('./chromedriver')
team1List = []
team2List = []
timeList = []
weather1List = []
weather2List = []
Shots1List = []
Shots2List = []
Fouls1List = []
Fouls2List = []
possession1List = []
possession2List = []

for i in range(94338,94340):
    url_base = 'http://www.football-lineups.com/match/'
    url_sub = str(i)
    driver.get(url_base + url_sub)
    html = driver.page_source
    soup = BeautifulSoup(html,'html.parser')
    team1 = soup.select('#mainarea > tbody > tr > td.TDmain > table > tbody > tr > td > font > b' )[0].text
    team1List.append(team1)
    team2 = soup.select('#mainarea > tbody > tr > td.TDmain > table > tbody > tr > td > font > b' )[1].text
    team2List.append(team2)
    time = soup.select('#mainarea > tbody > tr > td.TDmain > table > tbody > tr > td' )[6].text.split()
    timeList.append(time[0:2])
    weather = soup.select('#mainarea > tbody > tr > td.TDmain > table > tbody > tr > td > font' )[3:]
    weather1List.append(weather[0].text)
    weather2List.append(weather[1].text)
    detail = soup.select('#mainarea > tbody > tr > td.TDmain > table >\
                   tbody > tr > td > table > tbody > tr > td > table > tbody > tr > td' )[186:]
    Shots1List.append(detail[3].text)
    Shots2List.append(detail[5].text)
    Fouls1List.append(detail[6].text)
    Fouls2List.append(detail[8].text)
    possession1List.append(detail[15].text)
    possession2List.append(detail[17].text)

In [224]:
print(team1List)
print(team2List)
print(timeList)
print(weather1List)
print(weather2List)
print(Shots1List)
print(Shots2List)
print(Fouls1List)
print(Fouls2List)
print(possession1List)
print(possession2List)

['Japan', 'Uzbekistan']
['South Korea', 'Australia']
[['25-Jan-11', '16:25'], ['25-Jan-11', '19:25']]
[' 7:28 am AST  Fair 17C', ' 11:59 am AST  Fair 21C']
[' 4:28 pm AST  Fair 20C', ' 7:00 pm AST  Fair 19C']
['J Hwang (H Son)', '']
['', '']
['', '0-5']
['', '']
['', '']
['', '0-6']

In [225]:
gamedetail_sf_2011 = pd.DataFrame(team1List)
gamedetail_sf_2011 = gamedetail_sf_2011.rename(columns = {0:'team1'})
gamedetail_sf_2011['team2'] = team2List
gamedetail_sf_2011['gameday'] = timeList
gamedetail_sf_2011['weather_d'] = weather1List
gamedetail_sf_2011['weather_t'] = weather2List
gamedetail_sf_2011['shoot1'] = Shots1List
gamedetail_sf_2011['shoot2'] = Shots2List
gamedetail_sf_2011['foul1'] = Fouls1List
gamedetail_sf_2011['foul2'] = Fouls2List
gamedetail_sf_2011['possession1'] = possession1List
gamedetail_sf_2011['possession2'] = possession2List

In [226]:
gamedetail_sf_2011

,team1,team2,gameday,weather_d,weather_t,shoot1,shoot2,foul1,foul2,possession1,possession2
0,Japan,South Korea,"[25-Jan-11, 16:25]",7:28 am AST Fair 17C,4:28 pm AST Fair 20C,J Hwang (H Son),,,,,
1,Uzbekistan,Australia,"[25-Jan-11, 19:25]",11:59 am AST Fair 21C,7:00 pm AST Fair 19C,,,0-5,,,0-6

In [229]:
gamedetail_2011_t = pd.concat([gamedetail_2011_t,gamedetail_sf_2011])

In [231]:
# driver = webdriver.Chrome('./chromedriver')
team1List = []
team2List = []
timeList = []
weather1List = []
weather2List = []
Shots1List = []
Shots2List = []
Fouls1List = []
Fouls2List = []
possession1List = []
possession2List = []

for i in range(94404,94406):
    url_base = 'http://www.football-lineups.com/match/'
    url_sub = str(i)
    driver.get(url_base + url_sub)
    html = driver.page_source
    soup = BeautifulSoup(html,'html.parser')
    team1 = soup.select('#mainarea > tbody > tr > td.TDmain > table > tbody > tr > td > font > b' )[0].text
    team1List.append(team1)
    team2 = soup.select('#mainarea > tbody > tr > td.TDmain > table > tbody > tr > td > font > b' )[1].text
    team2List.append(team2)
    time = soup.select('#mainarea > tbody > tr > td.TDmain > table > tbody > tr > td' )[6].text.split()
    timeList.append(time[0:2])
    weather = soup.select('#mainarea > tbody > tr > td.TDmain > table > tbody > tr > td > font' )[3:]
    weather1List.append(weather[0].text)
    weather2List.append(weather[1].text)
    detail = soup.select('#mainarea > tbody > tr > td.TDmain > table >\
                   tbody > tr > td > table > tbody > tr > td > table > tbody > tr > td' )[186:]
    Shots1List.append(detail[3].text)
    Shots2List.append(detail[5].text)
    Fouls1List.append(detail[6].text)
    Fouls2List.append(detail[8].text)
    possession1List.append(detail[15].text)
    possession2List.append(detail[17].text)

In [232]:
print(team1List)
print(team2List)
print(timeList)
print(weather1List)
print(weather2List)
print(Shots1List)
print(Shots2List)
print(Fouls1List)
print(Fouls2List)
print(possession1List)
print(possession2List)

['Uzbekistan', 'Australia']
['South Korea', 'Japan']
[['28-Jan-11', '18:00'], ['29-Jan-11', '18:00']]
[' 10:00 am AST  Partly Cloudy 22C', ' 9:58 am AST  Fair 20C']
[' 11:59 am AST  Fair 22C', ' 6:00 pm AST  Clear 19C']
['5', '8']
['4', '3']
['15', '22']
['10', '14']
['57', '45']
['43', '55']

In [233]:
gamedetail_f_2011 = pd.DataFrame(team1List)
gamedetail_f_2011 = gamedetail_f_2011.rename(columns = {0:'team1'})
gamedetail_f_2011['team2'] = team2List
gamedetail_f_2011['gameday'] = timeList
gamedetail_f_2011['weather_d'] = weather1List
gamedetail_f_2011['weather_t'] = weather2List
gamedetail_f_2011['shoot1'] = Shots1List
gamedetail_f_2011['shoot2'] = Shots2List
gamedetail_f_2011['foul1'] = Fouls1List
gamedetail_f_2011['foul2'] = Fouls2List
gamedetail_f_2011['possession1'] = possession1List
gamedetail_f_2011['possession2'] = possession2List

In [234]:
gamedetail_f_2011

,team1,team2,gameday,weather_d,weather_t,shoot1,shoot2,foul1,foul2,possession1,possession2
0,Uzbekistan,South Korea,"[28-Jan-11, 18:00]",10:00 am AST Partly Cloudy 22C,11:59 am AST Fair 22C,5,4,15,10,57,43
1,Australia,Japan,"[29-Jan-11, 18:00]",9:58 am AST Fair 20C,6:00 pm AST Clear 19C,8,3,22,14,45,55

In [235]:
gamedetail_2011_t = pd.concat([gamedetail_2011_t,gamedetail_f_2011])

In [237]:
# gamedetail_2011_t.to_csv('./gamedetail_2011.csv',index=False,header=True)